### ISSUE TITLE
Should add static libraries to PBXFrameworksBuildPhase

### ISSUE THREAD

**Issue by twobitlabs** [keithpitt/vendor#11]
If a dependency includes a .a file, it should be added to the PBXFrameworksBuildPhase for the selected target, so the target will link against the library. This is what happens in Xcode when you add a static library to a target.

For example, if you include https://github.com/twobitlabs/AnalyticsKit, the following libraries should be linked: libApsalar.a, libFlurryAnalytics.a, libTestFlight.a, but they are not.

If you manually add them to the link files phase, they will be removed when you run `vendor install` again, so there is currently no good way to include a dependency with a static library.

**Comment by burtlo** [comment]
@twobitlabs this is definitely important to add. Since adding Xcoder as the parser, there is a lot of flexibility in being able to define source files, resource files, and other libraries. I'll get to work adding this functionality.

**Comment by burtlo** [comment]
@twobitlabs I have explicit build phases for resources and static library files, like `libTestFlight.a` specified in the files section will be added to the frameworks build phase.

https://github.com/keithpitt/vendor/commit/b04747b5e281dd9acb5575f5beb6452ed1ee3381#L4R42

**Comment by burtlo** [comment]
Now we just need support for custom frameworks.
