### ISSUE TITLE
Library added to all targets, not those specified

### ISSUE THREAD

**Issue by jasperblues** [keithpitt/vendor#12]
Steps to reproduce: 
1. Create a vendor file as follows: 

lib "ExpanzCore", :git => "git@github.com:expanz/expanz-iOS-SDK.git", :require => "Source/Main/Core"
# These lines are an alternative syntax to the target specification above

lib "ExpanzCore", :targets => [ "Model-Object-Explorer", "Tests" ]
1. vendor install

Expected Outcome: 

ExpanzCore.m files are added to "Model-Object-Explorer" and "Tests" targets. 

Actual Outcome: 

.m files are added to all targets in the project.

**Comment by burtlo** [comment]
This appears to be fixed now since the change over to Xcoder. I took this as a chance to update the debug output for the installation.
