### ISSUE TITLE
Readme shows an invalid git repo URL

### ISSUE THREAD

**Issue by jasperblues** [keithpitt/vendor#13]
Should the URL for AFNetworking in the Readme be 'git@github.com...AFNetworking' and not 'git://github.com....AFNetworking' ??

**Comment by burtlo** [comment]
I noticed that a most of the example README does not work. This definitely needs to be udpated.

**Comment by samritchie** [comment]
I've updated the AFNetworking url in the interests of clearing out the open issues. I'll review the rest of the README as part of the ever-lengtehning todo list.
