### ISSUE TITLE
Error converting the XCode project back to a Plist

### ISSUE THREAD

**Issue by gcerquant** [keithpitt/vendor#3]
I was trying to install RestKit into my iOS project.
It failed with an error : "**error converting the XCode project back to a Plist**"

Here is my Vendorfile:
$ `cat Vendorfile`
`# This is an example Vendorfile for you to start editing and add your`
`# own dependencies. Check out http://github.com/keithpitt/vendor for`
`# more information on how to use this file.`

`````` ```
```lib "RestKit", :git => "https://github.com/RestKit/RestKit.git"```

Then I run:
$ `vendor install`
```Fetching https://github.com/RestKit/RestKit.git
remote: Counting objects: 11513, done.
remote: Compressing objects: 100% (4311/4311), done.
remote: Total 11513 (delta 7651), reused 10542 (delta 6810)
Receiving objects: 100% (11513/11513), 30.41 MiB | 575 KiB/s, done.
Resolving deltas: 100% (7651/7651), done.
Installing RestKit (https://github.com/RestKit/RestKit.git#master)
Backup created ./MyApp.vendorbackup
There was an error converting the XCode project back to a Plist
#<Vendor::Plist::AsciiParser::ParseError: missing ';' in dictionary at line 294
"FAMILY = 1,2;\n};\n};\n "
>
Finished installing into MyApp```


Project was new (nothing edited in it after its creation). Created with Xcode 4.2.1 (Build 4D502).
``````

**Comment by gcerquant** [comment]
Some more information:

The steps to reproduce the bug are:
- Create a new project in Xcode (my version : 4.2.1 - 4D502 ; on Lion 10.7.2)
- Choose the iPhone template 'Single View Application'
- Create a Vendor file: `echo 'lib "ASIHTTPRequest", "~> 1.8"' > Vendorfile`
- Run `vendor install`
- Output of the command:
  `Installing ASIHTTPRequest 1.8.1
  Installing Reachability 2.0.4ddg
  Backup created ./TestVendorKit.vendorbackup.1`
  `There was an error converting the XCode project back to a Plist`
  `#<Vendor::Plist::AsciiParser::ParseError: missing ';' in dictionary at line 425`
  `"FAMILY = 1,2;\n};\n};\n "`
  `>`
  `Finished installing into TestVendorKit`

If needed, you can download the Xcode project created: http://dl.dropbox.com/u/1899122/www/keithpitt_vendor_issues_3/TestVendorKit.xcodeproj.zip

**Comment by gcerquant** [comment]
I updated to latest head (commit 7f9dea5830a9028b8291ad0d352afe5f83b0d4d9). I have cloned it in ~/Desktop/vendor. Then, being in the folder of my Xcode project, running `~/Desktop/vendor/bin/vendor install` still gives an error. But not the same one:  

```Installing RestKit (https://github.com/RestKit/RestKit.git#master)
Backup created ./Test.vendorbackup
There was an error converting the XCode project back to a Plist
#<Vendor::Plist::AsciiParser::ParseError: missing ';' in dictionary at line 1011
"  path = 1.json;\n  so"

> Finished installing into Test```

I appreciate the time you put into this issue. Thank you :)

**Comment by keithpitt** [comment]
Ahh, balls. My plist converter is pretty flaky by the looks of it. I'll fix that issue now.

**Comment by keithpitt** [comment]
Hrm, could you post the project your using? I'm having a hard time replicate this one...

**Comment by phuwanart** [comment]
I clone VendorKitTest from https://github.com/rauluranga/VendorKitTest. It dosen't have this problem but I create new project it has this error.

I use Xcode 4.2.1

**Comment by keithpitt** [comment]
I've done some fixes on this. Try master and let me know how you go.

**Comment by phuwanart** [comment]
I also have this problem.

```
$ vendor install
Installing ASIHTTPRequest 1.8.1
Installing JSONKit 1.4
Installing Reachability 2.0.4ddg
Backup created ./ETRShelfKit.vendorbackup
There was an error converting the XCode project back to a Plist
#<Vendor::Plist::AsciiParser::ParseError: missing ';' in dictionary at line 2083
"FAMILY = 1,2;\n};\n  na"
>
Finished installing into ETRShelfKit
```

**Comment by keithpitt** [comment]
I have pushed a new version of Vendor to rubygems. Update vendor and try again for me. Sorry about the hassle :D

**Comment by phuwanart** [comment]
Thank you very much. I update new gem version, it solve this problem.

Thank for you work. ^^

```
$ vendor install
Installing ASIHTTPRequest 1.8.1
Installing JSONKit 1.4
Installing Reachability 2.0.4ddg
Backup created ./ETRShelfKit.vendorbackup
Finished installing into ETRShelfKit
```

**Comment by keithpitt** [comment]
Great!

**Comment by gcerquant** [comment]
Keith, thank you for fixing this.
