### ISSUE TITLE
Vendor doesn't update it's cache of a git repo when url changes

### ISSUE THREAD

**Issue by rayh** [keithpitt/vendor#6]
I initially had a dependency set up as follows:

lib "TTTAttributedLabel", :git => "https://github.com/mattt/TTTAttributedLabel.git"

I then changed it to my own fork:

lib "TTTAttributedLabel", :git => "https://github.com/rayh/TTTAttributedLabel.git"

After doing a vendor install, the mattt version was still being used.  I eventually blew away ~/.vendor in order to clear the cache.

**Comment by keithpitt** [comment]
After looking into this issue, I found the following line:

https://github.com/keithpitt/vendor/blob/master/lib/vendor/vendor_file/library/git.rb#L47

I seem to have already catered for this. After testing it out, I couldn't reproduce the problem. Could you try again on a blank project for me?

**Comment by keithpitt** [comment]
I think this is fixed.
